apiVersion: v1 # Kubernetes API version for services
kind: Service # Kind of Kubernetes resource
metadata:
  name: my-app-service # Name of the service
spec:
  selector: # Selector to identify pods for the service
    app: my-app # Matches the label used in the deployment
  ports: # Service port definition
  - protocol: TCP # Protocol used by the service
    port: 80 # Port exposed by the service (can be different from container port)
    targetPort: 8080 # Port on the pods that the service forwards traffic to
  type: LoadBalancer # Service type (can be different based on needs)

